baseURL = "https://example.org/"
languageCode = "fr-ch"
title = "Elodie Perring"
theme = "digitalgarden"

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "My Digital Garden on the Internet"
  images = ['/images/favicon.ico']
  enableSearch = true


[menu]
[[menu.main]]
  name = 'Accueil'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'A propos'
  url = '/propos'
  weight = 2


[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/elodiePe/labveilletech'
  weight = 1
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://linkedin.com/elodieperring'
  weight = 2



# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
